kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: stainlessio/hugo:0.54.0
  commands:
  - hugo

- name: deploy
  image: plugins/s3
  settings:
    bucket: livecodeseattle.com
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: public/**/*
    target: /
    strip_prefix: public/
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
