kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: ubuntu:16.04
  privileged: true
  environment:
    HUGO_VERSION: "0.54.0"
  commands:
  - curl -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
  - apt install ./hugo.deb
  - hugo

- name: deploy
  image: plugins/s3
  settings:
    bucket: livecodeseattle.com
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: public/**/*
    target: /
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
